### ISSUE TITLE
payload setState

### ISSUE THREAD

**Issue by jena-boehm** [katherinemtam/resty-postman-clone#3]
I think this might have to be ` this.setState({ payload: payload });` 
so you're actually setting that payload state to what's returned from the fetch. currently the fetch results don't display in the Payload component

https://github.com/katherinemtam/resty-postman-clone/blob/4c96d6fcce69dd383966c1ea87e876ad192611b0/src/containers/Resty.jsx#L31

**Comment by katherinemtam** [comment]
Hmm...interesting. It's working on my end via the Netlify endpoint and localhost...
[
![resty1](https://user-images.githubusercontent.com/74214477/127931489-4d7d65e6-8cf6-4385-8fd6-299068443e1b.JPG)
![resty2](https://user-images.githubusercontent.com/74214477/127931502-2472903a-e355-491c-bcae-8d26e0331bb3.JPG)
](url)
